batteryqa/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.batteryqa, name='batteryqa-qa'),
    path('search/', views.batterysearch, name='batteryqa-search'),
    path('search-results/', views.search_results, name='batteryqa-search-results'),
    path('search-results/<int:example>', views.search_results_example, name='batteryqa-search-results-example'),
    path('answer/', views.answers, name='batteryqa-answer'),
    path('answer/<int:example>', views.answers_example, name='batteryqa-answer-example'),
    # path('test/', views.test, name='batteryqa-test'),
]

bdweb/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('data/', include('data.urls')),
    path('qa/', include('batteryqa.urls')),
    path('', include('about.urls')),
    path('classifier/', include('classifier.urls')),
    # path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    # path('register/', user_views.register, name='register'),
    # path('profile/', user_views.profile, name='profile'),
    # path('password-reset/',
    #      auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
    #      name='password_reset'),
    # path('password-reset/done/',
    #      auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
    #      name='password_reset_done'),
    # path('password-reset-comfirm/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
    #      name='password_reset_confirm'),
    # path('password-reset-complete/',
    #      auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
    #      name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

data/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.data, name='data-data'),
]

batteryqa/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Question(models.Model):
    MODEL = [('BatteryBERT-cased', 'BatteryBERT-cased'), ('BatterySciBERT-cased', 'BatterySciBERT-cased'),
             ('BatteryOnlyBERT-cased', 'BatteryOnlyBERT-cased'), ('BatteryBERT-uncased', 'BatteryBERT-uncased'),
             ('BatterySciBERT-uncased', 'BatterySciBERT-uncased'),
             ('BatteryOnlyBERT-uncased', 'BatteryOnlyBERT-uncased')]
    select = models.CharField(_('Select a model to analyse:'), choices=MODEL, max_length=25,
                              default='BatteryBERT-cased')
    confidence = models.FloatField(_('Confidence score threshold:'))
    ques = models.CharField(_('Ask a question:'), max_length=100)
    context = models.TextField(_(''))
    # answer = models.CharField(_('answer'), max_length=100, default='none')
    # score = models.FloatField(_('score'), default=0)

    class Meta:
        verbose_name = _('question')
        verbose_name_plural = _('questions')


class Search(models.Model):
    search = models.CharField(_(''), max_length=100)

batteryqa/forms.py
from django import forms
from .models import Question, Search


class QuestionForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True

    class Meta:
        model = Question
        fields = ['select', 'confidence', 'ques', 'context']
        widgets = {
            'ques': forms.TextInput(
                attrs={'placeholder': "Default: What's the device component? (Anode, cathode, electrolyte)",
                       "style": "width: 35rem;"}),
            'confidence': forms.TextInput(
                attrs={'placeholder': "0~1. Default: 0.3",
                       "style": "width: 9;"}),
            'context': forms.Textarea(
                attrs={'placeholder': "We have now dereprecated the interactive function, previously deprecated due to the large size of LLMs.\n"
                                      "For large-scale data extraction, please use the Python code of BatteryBERT and BatteryDataExtractor, and run extraction in parallel on an HPC machine for optimal performance.\n"}),
        }
        required = ['confidence', 'ques', 'context']


class SearchForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True

    class Meta:
        model = Search
        fields = ['search']
        widgets = {
            'search': forms.Textarea(
                attrs={'placeholder': "Example: What’s the most common electrolyte in 2019?\n"
                                        "We have now dereprecated the interactive function, previously deprecated due to the large size of LLMs.\n"
                                        "For large-scale data extraction, please use the Python code of BatteryBERT and BatteryDataExtractor, and run extraction in parallel on an HPC machine for optimal performance.\n"}),
                }
        required = ['search']

batteryqa/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from .forms import QuestionForm, SearchForm
from .tasks import run_qa, run_answer


# @login_required()
def batterysearch(request):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            question = data['search']
            records = run_answer(question)
            # print(records)
            outputs = {'records': records}
            request.session['search_results'] = outputs
            return redirect(search_results)
    else:
        form = SearchForm()
    return render(request, 'batteryqa/search.html', {'form': form, 'title': 'BatterySearch'})


# @login_required()
def search_results(request):
    outputs = request.session.get('search_results')
    # print(outputs)
    return render(request, 'batteryqa/search-results.html', outputs)


# @login_required()
def search_results_example(request, example):
    if example == 1:
        outputs = {'records': [{'original_question': "what's the most common anode in 2015 ", 'answer': 'graphite'}]}
    elif example == 2:
        outputs = {'records': [{'original_question': "what's the most common cathode in 2021 ", 'answer': 'sulfur'}]}
    elif example == 3:
        outputs = {'records': [{'original_question': "what's the most common electrolyte in 1999 ", 'answer': 'propylene carbonate'}]}
    elif example == 4:
        outputs = {'records': [{'original_question': 'No similar questions found', 'answer': 'No answers found. Ask me some questions about batteries.'}]}
    return render(request, 'batteryqa/search-results.html', outputs)


# @login_required()
def batteryqa(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            records = run_qa(data['select'], data['ques'], data['confidence'], data['context'])
            # print(records)
            outputs = {'records': records}
            request.session['outputs'] = outputs
            return redirect(answers)
    else:
        form = QuestionForm()
    return render(request, 'batteryqa/qa.html', {'form': form, 'title': 'BatteryQA'})


# @login_required()
def answers(request):
    outputs = request.session.get('outputs')
    return render(request, 'batteryqa/answers.html', outputs)


# @login_required()
def answers_example(request, example):
    if example == 1:
        records = [{'type': 'cathode', 'answer': 'lithium iron phosphate', 'score': 0.7359284162521362, 'context':
                    'The lithium iron phosphate battery (LiFePO4 battery) or LFP battery (lithium ferrophosphate), '
                    'is a type of lithium-ion battery using lithium iron phosphate (LiFePO4) as the cathode material, '
                    'and a graphitic carbon electrode with a metallic backing as the anode.'},
                   {'type': 'anode', 'answer': 'graphitic carbon electrode with a metallic backing',
                    'score': 0.34201282262802124, 'context':
                    'The lithium iron phosphate battery (LiFePO4 battery) or LFP battery (lithium ferrophosphate), '
                    'is a type of lithium-ion battery using lithium iron phosphate (LiFePO4) as the cathode material, '
                    'and a graphitic carbon electrode with a metallic backing as the anode.'}]
        outputs = {'records': records}
        return render(request, 'batteryqa/answers.html', outputs)
    elif example == 2:
        records = [{'type': 'electrolyte', 'answer': 'a solution of LiPF6 in linear and cyclic carbonates',
                    'score': 0.19098393619060516, 'context':
                    'The typical non-aqueous electrolyte for commercial Li-ion cells is a solution of LiPF6 in linear '
                    'and cyclic carbonates such as dimethyl carbonate and ethylene carbonate, respectively [1], [2].'}]
        outputs = {'records': records}
        return render(request, 'batteryqa/answers.html', outputs)
    elif example == 3:
        records = [{'type': "What's the maximum capacity of LiC6?", 'answer': '372 mAh g−1',
                    'score': 0.6613584756851196, 'context':
                    'The mechanism of lithium intercalation in the so-called ‘soft’ anodes, i.e. graphite or '
                    'graphitable carbons, is well known: it develops through well-identified, reversible stages, '
                    'corresponding to progressive intercalation within discrete graphene layers, to reach the '
                    'formation of LiC6 with a maximum theoretical capacity of 372 mAh g−1.'}]
        outputs = {'records': records}
        return render(request, 'batteryqa/answers.html', outputs)
    elif example == 4:
        records = [{'type': "What is a possible application for NCA cathode?", 'answer': 'electric vehicles',
                    'score': 0.13558681309223175, 'context':
                        "For current LIBs based on OLE system, the employed cathodes could be mainly divided into two "
                        "categories: LCO is still very popular in the consumer electronics market and Ni-rich "
                        "compounds have already taken a place in the electric vehicles where the Tesla "
                        "LiNi0.8Co0.15Al0.05O2 (NCA) cathode is a good example."}]
        outputs = {'records': records}
        return render(request, 'batteryqa/answers.html', outputs)

batteryqa/templates/batteryqa/answers.html
{% extends "about/base.html" %}

{% load macros %}

{% block title %}QA Results | Battery Data{% endblock %}

{% macro display_record record %}
<div class="card mb-3 border rounded-lg" style="width: 38rem;">
  {% if record.type == 'cathode' %}
  <div class="card-header p-3 mb-2 bg-dark text-white">Question: {{ record.type|capfirst }}</div>
  {% elif record.type == 'anode'%}
  <div class="card-header p-3 mb-2 bg-secondary text-white">Question: {{ record.type|capfirst }}</div>
  {% else %}
  <div class="card-header p-3 mb-2 bg-info text-white">Question: {{ record.type|capfirst }}</div>
  {% endif %}
  <div class="card-body text-dark">
    <h5 class="card-title">Answer: {{ record.answer }}</h5>
    <p class="card-text"><b>Context: </b>{{ record.context }}</p>
    <p class="card-text"><b>Confidence score: </b>{{ record.score }}</p>
{#    <p><b>DOI: </b>  {{ record['doi'] }}</p>#}
  </div>
</div>
{% endmacro %}
<a href="#" class="card-link">Card link</a>

{% block content %}
  <div class="container page-container">
      <div class="col-sm-12">
        <h1 class="font-weight-normal">Results</h1>
    </div>
    <div class="row">
      <div class="col-sm-12">
          <div> 
              <div class="col-sm-8">
              </div>
                  <div>
                    {% if records %}
                    {% for output in records %}
                        {% use_macro display_record output %}
                    {% endfor %}
                    {% else %}
                    <p class="alert alert-primary text-note"> No results found! <br> Try to set a lower confidence score?</p>{% endif %}
                  </div>
              </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{#{% block scripts %}#}
{#  {{ super() }}#}
{#  <script>#}
{#    var jobId = '{{ job.job_id }}';#}
{#  </script>#}
{#  <script src="{{ url_for('static', filename='js/results.js') }}"></script>#}
{#{%- endblock scripts %}#}

batteryqa/templates/batteryqa/qa.html
{% extends "about/base.html" %}

{% load crispy_forms_tags %}

{% block title %}Data Extraction | Battery Data{% endblock %}

{% block content %}
  <div class="container page-container">
    <h1 class="font-weight-normal" style="color: #002b04">BatteryQA</h1>
      <p>Enter text as context for questions, or upload a paper from RSC, Elsevier, or Springer journal.</p>

      <form class="form" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
      <div class="form-inline">
          <div class="form-group">
          <div class="input-group input-group-sm mb-2 mr-sm-2">
              {{ form.select|as_crispy_field  }}
          </div>
        </div>
          {{ form.confidence|as_crispy_field  }}
          <div class="form-group ">
              {{ form.ques|as_crispy_field  }}
        </div>
      </div>
      <br>


      <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link" id="text-tab" data-toggle="tab" href="#tab-text" role="tab" aria-controls="text" aria-selected="false">Enter text</a>
        </li>
          <li class="nav-item">
            <a class="nav-link active" id="example-tab" data-toggle="tab" href="#tab-example" role="tab" aria-controls="example" aria-selected="true">Examples</a>
        </li>
{#          <li class="nav-item">#}
{#            <a class="nav-link" id="home-tab" data-toggle="tab" href="#tab-file" role="tab" aria-controls="home" aria-selected="true">Upload a file</a>#}
{#        </li>#}
      </ul>
    <div>
      <div class="tab-content">
{#        <div role="tabpanel" class="tab-pane" id="tab-file">#}
{#              <div class="form-group">#}
{#              <div class="input-group">#}
{#                <span class="input-group-btn">#}
{#                  <span class="btn btn-default btn-file">Browse a file&hellip;<input type="file" name="input-file"></span>#}
{#                </span>#}
{#                <input type="text" class="form-control" readonly>#}
{#              </div>#}
{#            </div>#}
{##}
{#         <div class="form-group">#}
{#            <button id="submit-file" class="btn btn-lg btn-primary ">Submit</button>#}
{#          </div>#}
{#        </div>#}
      <div role="tabpanel" class="tab-pane" id="tab-text">
{#          <div class="form-group">#}
{#            <textarea id="id_context" name="context" class="form-control" placeholder="Type or paste text in here... &#10;Example: The cathode of this Li-ion battery system is LiFePO4."></textarea>#}
{#          </div>#}
          {{ form.context|as_crispy_field }}
          <div class="form-group">
            <button id="id_submit" class="btn btn-outline-dark mr-2" disabled>Submit</button>
          </div>
      </div>

      <div role="tabpanel" class="tab-pane active" id="tab-example">

        <div class="panel panel-default panel-results">
            <div class="row">
                <div class="col-xs-12 col-sm-10">
                  <img class="doc-icon" src="/static/images/document.svg">
                  <div class="doc-meta">
                      <p> <strong>Question:</strong> What's the device component?</p>
                    <p class="text-tiny">
                            <strong>Context:</strong> The lithium iron phosphate battery (LiFePO4 battery) or LFP battery (lithium ferrophosphate), is a type of lithium-ion battery using lithium iron phosphate (LiFePO4) as the cathode material, and a graphitic carbon electrode with a metallic backing as the anode.
                     </p>
                      <p class="alert alert-success text-note">
                         <strong>Device data extraction example:</strong> Extract anode and cathode materials.
                        <strong>Source: </strong>
                            <a href="https://en.wikipedia.org/wiki/Lithium_iron_phosphate_battery">Wikipedia</a>
                      </p>
                  </div>
                </div>
                <div class="col-xs-12 col-sm-2">
                  <a class="btn btn-success btn-sm btn-result" href="{% url 'batteryqa-answer-example' 1 %}">Show Results <i class="glyphicon glyphicon-chevron-right"></i></a>
                </div>
              </div>
          </div>
          <div class="panel panel-default panel-results">
        <div class="row">
                <div class="col-xs-12 col-sm-10">
                  <img class="doc-icon" src="/static/images/document.svg">
                  <div class="doc-meta">
                      <p> <strong>Question:</strong> What's the electrolyte?</p>
                    <p class="text-tiny">
                            <strong>Context:</strong>  The typical non-aqueous electrolyte for commercial Li-ion cells is a solution of LiPF6 in linear and cyclic carbonates such as dimethyl carbonate and ethylene carbonate, respectively [1], [2].
                     </p>
                      <p class="alert alert-success text-note">
                         <strong>Device data extraction example:</strong> Extract electrolyte materials.
                        <strong>Source: </strong>
                            <a href="https://doi.org/10.1016/S0378-7753(03)00149-6">10.1016/S0378-7753(03)00149-6</a>
                      </p>
                  </div>
                </div>
                <div class="col-xs-12 col-sm-2">
                  <a class="btn btn-success btn-sm btn-result" href="{% url 'batteryqa-answer-example' 2 %}">Show Results <i class="glyphicon glyphicon-chevron-right"></i></a>
                </div>
              </div>
          </div>
          <div class="row">
                <div class="col-xs-12 col-sm-10">
                  <img class="doc-icon" src="/static/images/cde-logo.svg">
                  <div class="doc-meta">
                      <p> <strong>Question:</strong> What's the maximum capacity of LiC6?</p>
                    <p class="text-tiny">
                           <strong>Context:</strong>   The mechanism of lithium intercalation in the so-called ‘soft’ anodes, i.e. graphite or graphitable carbons, is well known: it develops through well-identified, reversible stages, corresponding to progressive intercalation within discrete graphene layers, to reach the formation of LiC6 with a maximum theoretical capacity of 372 mAh g−1.
                    </p>
                      <p class="alert alert-warning text-note">
                          <strong>General QA example: </strong>extract property data.
                        <strong>Source: </strong>
                            <a href="https://doi.org/10.1016/S0013-4686(00)00333-9">10.1016/S0013-4686(00)00333-9</a>
                      </p>
                  </div>
                </div>
                <div class="col-xs-12 col-sm-2">
                  <a class="btn btn-warning btn-sm btn-result" href="{% url 'batteryqa-answer-example' 3 %}">Show Results <i class="glyphicon glyphicon-chevron-right"></i></a>
                </div>
              </div>
                    <div class="row">
                <div class="col-xs-12 col-sm-10">
                  <img class="doc-icon" src="/static/images/cde-logo.svg">
                  <div class="doc-meta">
                      <p> <strong>Question:</strong> Which cathode is commonly used in electric vehicles?</p>
                    <p class="text-tiny">
                            <strong>Context:</strong>  For current LIBs based on OLE system, the employed cathodes could be mainly divided into two categories: LCO is still very popular in the consumer electronics market and Ni-rich compounds have already taken a place in the electric vehicles where the Tesla LiNi0.8Co0.15Al0.05O2 (NCA) cathode is a good example.
                    </p>
                      <p class="alert alert-warning text-note">
                         <strong>General QA example:</strong> Get the application of a battery material.
                        <strong>Source: </strong>
                            <a href="https://doi.org/10.1016/j.ensm.2019.05.019">10.1016/j.ensm.2019.05.019</a>
                      </p>
                  </div>
                </div>
                <div class="col-xs-12 col-sm-2">
                  <a class="btn btn-warning btn-sm btn-result" href="{% url 'batteryqa-answer-example' 4 %}">Show Results <i class="glyphicon glyphicon-chevron-right"></i></a>
                </div>
              </div>
          </div>
          </div>
      </div>

      </div>
    </div>
      </form>
  </div>
{% endblock %}


{#{% block scripts %}#}
{#  {{ super() }}#}
{#  <script src="{{ url_for('static', filename='js/demo.js') }}"></script>#}
{#{% endblock scripts %}#}

batteryqa/templates/batteryqa/results.html
{% extends "about/base.html" %}

{% block title %}QA Results | Battery Data{% endblock %}

{% macro display_record(record, index) %}   
<div class="card mb-3 border rounded-lg" style="width: 38rem;">
  {% if record['type']=='cathode' %}
  <div class="card-header p-3 mb-2 bg-dark text-white">Component: {{ record['type'].capitalize() }}</div>
  {% elif record['type']=='anode'%}
  <div class="card-header p-3 mb-2 bg-secondary text-white">Component: {{ record['type'].capitalize() }}</div>
  {% else %}
  <div class="card-header p-3 mb-2 bg-info text-white">Component: {{ record['type'].capitalize() }}</div>
  {% endif %}
  <div class="card-body text-dark">
    <h5 class="card-title">Material: {{ record['answer'] }}</h5>
    <p class="card-text"><b>Context: </b>{{ record['context'] }}</p>
    <p class="card-text"><b>Confidence score: </b>{{ record['score'] }}</p>
    <p><b>DOI: </b>  {{ record['doi'] }}</p>
  </div>
</div>
{% endmacro %}<a href="#" class="card-link">Card link</a>

{% block content %}
  <div class="container page-container">
      <div class="col-sm-12">
        <h1>Results</h1>
    </div>
    <div class="row">
      <div class="col-sm-12">
          <div> 
              <div class="col-sm-8">
              </div>
                  <div>
                    {% if outputs %}
                    {% for output in outputs %}
                      {{ display_record(output, loop.index0) }}
                    {% endfor %}
                    {% else %}
                    <p> No results found!</p>
                    {% endif %}
                  </div>
              </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{#{% block scripts %}#}
{#  {{ super() }}#}
{#  <script>#}
{#    var jobId = '{{ job.job_id }}';#}
{#  </script>#}
{#  <script src="{{ url_for('static', filename='js/results.js') }}"></script>#}
{#{%- endblock scripts %}#}

batteryqa/templates/batteryqa/search-results.html
{% extends "about/base.html" %}

{% load macros %}

{% block title %}Search Results | Battery Data{% endblock %}

{% macro display_record record %}
    <div class="jumbotron jumbotron-fluid">
      <h5 class="display-14">Answer: {{ record.answer|capfirst }}</h5>
      <p class="lead">Source: {{ record.original_question|capfirst }} from the dataset</p>
    </div>
{% endmacro %}
{#<a href="#" class="card-link">Card link</a>#}

{% block content %}
  <div class="container page-container">
{#        <h3>Question: {{ questions }} </h3>#}
    <div class="row">
      <div class="col-sm-12">
              <div class="col-sm-8">
              </div>
                  <div>
                    {% if records %}
                    {% for output in records %}
                      {% use_macro display_record output %}
                      {% endfor %}
                    {% else %}
                    <p> No results found!</p>
                    {% endif %}
                  </div>
              </div>
      </div>
    </div>
  </div>
{% endblock %}

{#{% block scripts %}#}
{#  {{ super() }}#}
{#  <script>#}
{#    var jobId = '{{ job.job_id }}';#}
{#  </script>#}
{#  <script src="{{ url_for('static', filename='js/results.js') }}"></script>#}
{#{%- endblock scripts %}#}

batteryqa/templates/batteryqa/test.html
{% extends "about/base.html" %}

{% load crispy_forms_tags %}

{% block title %}Data Extraction | Battery Data{% endblock %}

{% block content %}
  <div class="container page-container">
    <h1>BatteryQA</h1>
      <p>Enter text as context for questions, or upload a paper from RSC, Elsevier, or Springer journal.</p>

      <form class="form" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
{#          {{ form.as_ul }}#}
      <div class="form-inline">
{#        <div class="mb-2 mr-sm-2">Select a model to analyse:</div >#}
          <div class="form-group">
          <div class="input-group input-group-sm mb-2 mr-sm-2">
{#            <select id="id_select" name="select" class="custom-select" style="width: 10rem;">#}
{#              <option selected>BatteryBERT</option>#}
{#              <option value="BatterySciBERT">BatterySciBERT</option>#}
{#              <option value="BatteryOnlyBERT">BatteryOnlyBERT</option>#}
{#            </select>#}
              {{ form.select|as_crispy_field  }}
          </div>
        </div>
{#        <div class="mb-2 mr-sm-2">Confidence score threshold:</div >#}
{#        <input type="number step=any" class="form-control mb-2 mr-sm-2" id="id_confidence" name="confidence" placeholder="0~1. Default: 0.3" style="width: 9rem;"  >#}
            {{ form.confidence|as_crispy_field  }}
          <div class="form-group ">
{#            <p class="mb-2 mr-sm-3">Ask a question: </p>#}
{#            <input type="text" class="form-control mb-2 mr-sm-5" id="id_ques" name="ques" placeholder="Default: What's the device component? (Anode, cathode, electrolyte)" style="width: 35rem;" >#}
        {{ form.ques|as_crispy_field  }}
        </div>
      </div>
      <br>


      <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="text-tab" data-toggle="tab" href="#tab-text" role="tab" aria-controls="text" aria-selected="false">Enter text</a>
        </li>
          <li class="nav-item">
            <a class="nav-link" id="example-tab" data-toggle="tab" href="#tab-example" role="tab" aria-controls="example" aria-selected="true">Examples</a>
        </li>
{#          <li class="nav-item">#}
{#            <a class="nav-link" id="home-tab" data-toggle="tab" href="#tab-file" role="tab" aria-controls="home" aria-selected="true">Upload a file</a>#}
{#        </li>#}
      </ul>
    <div>
      <div class="tab-content">
{#        <div role="tabpanel" class="tab-pane" id="tab-file">#}
{#              <div class="form-group">#}
{#              <div class="input-group">#}
{#                <span class="input-group-btn">#}
{#                  <span class="btn btn-default btn-file">Browse a file&hellip;<input type="file" name="input-file"></span>#}
{#                </span>#}
{#                <input type="text" class="form-control" readonly>#}
{#              </div>#}
{#            </div>#}
{##}
{#         <div class="form-group">#}
{#            <button id="submit-file" class="btn btn-lg btn-primary ">Submit</button>#}
{#          </div>#}
{#        </div>#}
      <div role="tabpanel" class="tab-pane active" id="tab-text">
{#          <div class="form-group">#}
{#            <textarea id="id_context" name="context" class="form-control" placeholder="Type or paste text in here... &#10;Example: The cathode of this Li-ion battery system is LiFePO4."></textarea>#}
{#          </div>#}
          {{ form.context|as_crispy_field }}
          <div class="form-group">
            <button id="id_submit" class="btn btn-lg btn-primary">Submit</button>
          </div>
      </div>

      <div role="tabpanel" class="tab-pane" id="tab-example">

        <div class="panel panel-default panel-results">
            <div class="row">
                <div class="col-xs-12 col-sm-10">
                  <img class="doc-icon" src="/static/images/document.svg">
                  <div class="doc-meta">
                    <p class="text-tiny">
                             Boc-4-piperidone has a melting point of 73-77 °C, according to ChemSpider.
                             It has a density of 129.1 gcm-3. Completely unrelated, caffeine has a refractive index of 1.679.
                             Let's use this spot to look at the bandgap, Ω.
                             If we use a different material, such as SiO2 (L1), with a high Ω of 2.332(11) meV, at a thickness of 35 pm we can get good results.
                     </p>
                      <p class="alert alert-info text-note">
                        <strong>Note: </strong>
                            You can try 45 other properties like that, or build models quickly yourself. It's just 3-5 lines of code per model!
                      </p>
                  </div>
                </div>
                <div class="col-xs-12 col-sm-2">
                  <a class="btn btn-primary btn-result" href="/results/012bf3a6-eea8-4c40-9af6-a23c57e7b73a">Show Results <i class="glyphicon glyphicon-chevron-right"></i></a>
                </div>
              </div>
          </div>
          <div class="panel panel-default panel-results">
        <div class="row">
                <div class="col-xs-12 col-sm-10">
                  <img class="doc-icon" src="/static/images/document.svg">
                  <div class="doc-meta">
                    <p class="text-tiny">
                             Boc-4-piperidone has a melting point of 73-77 °C, according to ChemSpider.
                             It has a density of 129.1 gcm-3. Completely unrelated, caffeine has a refractive index of 1.679.
                             Let's use this spot to look at the bandgap, Ω.
                             If we use a different material, such as SiO2 (L1), with a high Ω of 2.332(11) meV, at a thickness of 35 pm we can get good results.
                     </p>
                      <p class="alert alert-info text-note">
                        <strong>Note: </strong>
                            You can try 45 other properties like that, or build models quickly yourself. It's just 3-5 lines of code per model!
                      </p>
                  </div>
                </div>
                <div class="col-xs-12 col-sm-2">
                  <a class="btn btn-primary btn-result" href="/results/012bf3a6-eea8-4c40-9af6-a23c57e7b73a">Show Results <i class="glyphicon glyphicon-chevron-right"></i></a>
                </div>
              </div>
          </div>
      </div>

      </div>
    </div>
      </form>
  </div>
{% endblock %}


{#{% block scripts %}#}
{#  {{ super() }}#}
{#  <script src="{{ url_for('static', filename='js/demo.js') }}"></script>#}
{#{% endblock scripts %}#}